### ISSUE TITLE
Add seaice to wrf ingestion.

### ISSUE THREAD

**Issue by bschroeter** [coecms/era5grib#8]
I could be wrong, but it doesn't look like seaice "ci" is included anywhere in the data acquisition for WRF. For high-latitude cases this would be ideal - perhaps as an override `--seaice`?

**Comment by ScottWales** [comment]
It should be included in the output already - https://github.com/coecms/era5grib/blob/master/era5grib/nci.py#L270. Do you have an output file where it's missing?

**Comment by bschroeter** [comment]
Sorry @ScottWales, the issue was in my namelist. You are correct, ci is included in the scripts.

Closing.
